CREATE TABLE mytable(
   id        INTEGER  NOT NULL PRIMARY KEY 
  ,Questions VARCHAR(100) NOT NULL
);
INSERT INTO mytable(id,Questions) VALUES (1,'15q overgrowth syndrome');
INSERT INTO mytable(id,Questions) VALUES (2,'17q11 microdeletion syndrome');
INSERT INTO mytable(id,Questions) VALUES (3,'ABeta amyloidosis, Dutch type');
INSERT INTO mytable(id,Questions) VALUES (4,'ABeta amyloidosis, Italian type');
INSERT INTO mytable(id,Questions) VALUES (5,'ABetaL34V amyloidosis');
INSERT INTO mytable(id,Questions) VALUES (6,'Acquired aneurysmal subarachnoid hemorrhage');
INSERT INTO mytable(id,Questions) VALUES (7,'Acquired methemoglobinemia');
INSERT INTO mytable(id,Questions) VALUES (8,'Acromegaly');
INSERT INTO mytable(id,Questions) VALUES (9,'Acute disseminated encephalomyelitis');
INSERT INTO mytable(id,Questions) VALUES (10,'Adenohypophysitis');
INSERT INTO mytable(id,Questions) VALUES (11,'Adiposis dolorosa');
INSERT INTO mytable(id,Questions) VALUES (12,'Adrenocortical carcinoma with pure aldosterone hypersecretion');
INSERT INTO mytable(id,Questions) VALUES (13,'Adult-onset chronic progressive external ophthalmoplegia with mitochondrial myopathy');
INSERT INTO mytable(id,Questions) VALUES (14,'Advanced sleep phase syndrome, familial, 2');
INSERT INTO mytable(id,Questions) VALUES (15,'African trypanosomiasis');
INSERT INTO mytable(id,Questions) VALUES (16,'Aicardi-Goutières syndrome');
INSERT INTO mytable(id,Questions) VALUES (17,'Alpha-methylacyl-CoA racemase deficiency');
INSERT INTO mytable(id,Questions) VALUES (18,'Alternating hemiplegia of childhood');
INSERT INTO mytable(id,Questions) VALUES (19,'Alternating hemiplegia of childhood 1');
INSERT INTO mytable(id,Questions) VALUES (20,'Alveolar echinococcosis');
INSERT INTO mytable(id,Questions) VALUES (21,'American trypanosomiasis');
INSERT INTO mytable(id,Questions) VALUES (22,'Amoebiasis due to free-living amoebae');
INSERT INTO mytable(id,Questions) VALUES (23,'Amyloidosis, hereditary, transthyretin-related');
INSERT INTO mytable(id,Questions) VALUES (24,'Aneurysm-osteoarthritis syndrome');
INSERT INTO mytable(id,Questions) VALUES (25,'Angiomatosis, diffuse corticomeningeal, of divry and van bogaert');
INSERT INTO mytable(id,Questions) VALUES (26,'Angiostrongyliasis');
INSERT INTO mytable(id,Questions) VALUES (27,'Aortic arch interruption');
INSERT INTO mytable(id,Questions) VALUES (28,'Arachnoid cyst');
INSERT INTO mytable(id,Questions) VALUES (29,'Arachnoiditis');
INSERT INTO mytable(id,Questions) VALUES (30,'Arnold-Chiari malformation type I');
INSERT INTO mytable(id,Questions) VALUES (31,'Arnold-Chiari malformation type II');
INSERT INTO mytable(id,Questions) VALUES (32,'Arteritis, familial granulomatous, with juvenile polyarthritis');
INSERT INTO mytable(id,Questions) VALUES (33,'Aspergillosis');
INSERT INTO mytable(id,Questions) VALUES (34,'Atrial standstill');
INSERT INTO mytable(id,Questions) VALUES (35,'Atypical teratoid rhabdoid tumor');
INSERT INTO mytable(id,Questions) VALUES (36,'Autoerythrocyte sensitization syndrome');
INSERT INTO mytable(id,Questions) VALUES (37,'Autoimmune hemolytic anemia');
INSERT INTO mytable(id,Questions) VALUES (38,'Autoimmune hemolytic anemia, warm type');
INSERT INTO mytable(id,Questions) VALUES (39,'Autoimmune lymphoproliferative syndrome');
INSERT INTO mytable(id,Questions) VALUES (40,'Autosomal dominant epilepsy with auditory features');
INSERT INTO mytable(id,Questions) VALUES (41,'Autosomal dominant optic atrophy plus syndrome');
INSERT INTO mytable(id,Questions) VALUES (42,'Autosomal dominant optic atrophy, classic form');
INSERT INTO mytable(id,Questions) VALUES (43,'Autosomal dominant progressive external ophthalmoplegia');
INSERT INTO mytable(id,Questions) VALUES (44,'Avian influenza');
INSERT INTO mytable(id,Questions) VALUES (45,'Babesiosis');
INSERT INTO mytable(id,Questions) VALUES (46,'Baralle-Macken syndrome');
INSERT INTO mytable(id,Questions) VALUES (47,'Basal ganglia calcification, idiopathic, 4');
INSERT INTO mytable(id,Questions) VALUES (48,'Basal ganglia calcification, idiopathic, 5');
INSERT INTO mytable(id,Questions) VALUES (49,'Basal ganglia calcification, idiopathic, 7, autosomal recessive');
INSERT INTO mytable(id,Questions) VALUES (50,'Behçet disease');
INSERT INTO mytable(id,Questions) VALUES (51,'Benign adult familial myoclonic epilepsy');
INSERT INTO mytable(id,Questions) VALUES (52,'Benign occipital epilepsy');
INSERT INTO mytable(id,Questions) VALUES (53,'Benign paroxysmal torticollis of infancy');
INSERT INTO mytable(id,Questions) VALUES (54,'Bernard-Soulier syndrome');
INSERT INTO mytable(id,Questions) VALUES (55,'Boutonneuse fever');
INSERT INTO mytable(id,Questions) VALUES (56,'Brain small vessel disease 1 with or without ocular anomalies');
INSERT INTO mytable(id,Questions) VALUES (57,'Bronchogenic cyst');
INSERT INTO mytable(id,Questions) VALUES (58,'Brucellosis');
INSERT INTO mytable(id,Questions) VALUES (59,'Brunner syndrome');
INSERT INTO mytable(id,Questions) VALUES (60,'Burning mouth syndrome');
INSERT INTO mytable(id,Questions) VALUES (61,'CACH syndrome');
INSERT INTO mytable(id,Questions) VALUES (62,'Camurati-Engelmann disease');
INSERT INTO mytable(id,Questions) VALUES (63,'Capillary malformation-arteriovenous malformation');
INSERT INTO mytable(id,Questions) VALUES (64,'Carney triad');
INSERT INTO mytable(id,Questions) VALUES (65,'Carnitine palmitoyl transferase II deficiency, severe infantile form');
INSERT INTO mytable(id,Questions) VALUES (66,'Carnitine palmitoyltransferase II deficiency');
INSERT INTO mytable(id,Questions) VALUES (67,'Catastrophic antiphospholipid syndrome');
INSERT INTO mytable(id,Questions) VALUES (68,'Central diabetes insipidus');
INSERT INTO mytable(id,Questions) VALUES (69,'Central neurocytoma');
INSERT INTO mytable(id,Questions) VALUES (70,'Cerebral arteriopathy, autosomal dominant, with subcortical infarcts and leukoencephalopathy, type 2');
INSERT INTO mytable(id,Questions) VALUES (71,'Cerebral arteriopathy, autosomal dominant, with subcortical infarctsand leukoencephalopathy');
INSERT INTO mytable(id,Questions) VALUES (72,'Cerebral autosomal dominant arteriopathy-subcortical infarcts-leukoencephalopathy');
INSERT INTO mytable(id,Questions) VALUES (73,'Cerebral cavernous malformations 1');
INSERT INTO mytable(id,Questions) VALUES (74,'Cerebral cavernous malformations 2');
INSERT INTO mytable(id,Questions) VALUES (75,'Cerebral cavernous malformations 3');
INSERT INTO mytable(id,Questions) VALUES (76,'Charcot-Marie-Tooth disease, axonal, type 2HH');
INSERT INTO mytable(id,Questions) VALUES (77,'Chiari malformation type I');
INSERT INTO mytable(id,Questions) VALUES (78,'Chiari malformation type II');
INSERT INTO mytable(id,Questions) VALUES (79,'Chikungunya');
INSERT INTO mytable(id,Questions) VALUES (80,'Chromosome Xq26.3 duplication syndrome');
INSERT INTO mytable(id,Questions) VALUES (81,'Ciliary dyskinesia, primary, 1');
INSERT INTO mytable(id,Questions) VALUES (82,'CINCA syndrome');
INSERT INTO mytable(id,Questions) VALUES (83,'Citrullinemia type I');
INSERT INTO mytable(id,Questions) VALUES (84,'Classic glucose transporter type 1 deficiency syndrome');
INSERT INTO mytable(id,Questions) VALUES (85,'Classic Hodgkin lymphoma');
INSERT INTO mytable(id,Questions) VALUES (86,'Classical Ehlers-Danlos syndrome');
INSERT INTO mytable(id,Questions) VALUES (87,'Cluster headache, familial');
INSERT INTO mytable(id,Questions) VALUES (88,'Coccidioidomycosis');
INSERT INTO mytable(id,Questions) VALUES (89,'Cold agglutinin disease');
INSERT INTO mytable(id,Questions) VALUES (90,'Combined malonic and methylmalonic acidemia');
INSERT INTO mytable(id,Questions) VALUES (91,'Combined oxidative phosphorylation deficiency 36');
INSERT INTO mytable(id,Questions) VALUES (92,'Combined oxidative phosphorylation deficiency 54');
INSERT INTO mytable(id,Questions) VALUES (93,'Congenital bile acid synthesis defect type 4');
INSERT INTO mytable(id,Questions) VALUES (94,'Congenital dyserythropoietic anemia type III');
INSERT INTO mytable(id,Questions) VALUES (95,'Congenital fiber-type disproportion myopathy');
INSERT INTO mytable(id,Questions) VALUES (96,'Craniodiaphyseal dysplasia, autosomal dominant');
INSERT INTO mytable(id,Questions) VALUES (97,'Craniofaciofrontodigital syndrome');
INSERT INTO mytable(id,Questions) VALUES (98,'Craniopharyngioma');
INSERT INTO mytable(id,Questions) VALUES (99,'Craniosynostosis 2');
INSERT INTO mytable(id,Questions) VALUES (100,'Crimean-Congo hemorrhagic fever');
INSERT INTO mytable(id,Questions) VALUES (101,'Crouzon syndrome');
INSERT INTO mytable(id,Questions) VALUES (102,'Crouzon syndrome-acanthosis nigricans syndrome');
INSERT INTO mytable(id,Questions) VALUES (103,'Cryptococcosis');
INSERT INTO mytable(id,Questions) VALUES (104,'Cushing disease');
INSERT INTO mytable(id,Questions) VALUES (105,'Cutaneous mastocytoma');
INSERT INTO mytable(id,Questions) VALUES (106,'Cyclic neutropenia');
INSERT INTO mytable(id,Questions) VALUES (107,'Cyclic vomiting syndrome');
INSERT INTO mytable(id,Questions) VALUES (108,'Deafness, autosomal dominant 34, with or without inflammation');
INSERT INTO mytable(id,Questions) VALUES (109,'Deafness, sensorineural, with peripheral neuropathy and arterial disease');
INSERT INTO mytable(id,Questions) VALUES (110,'Deafness-lymphedema-leukemia syndrome');
INSERT INTO mytable(id,Questions) VALUES (111,'Dengue fever');
INSERT INTO mytable(id,Questions) VALUES (112,'Diffuse cutaneous mastocytosis');
INSERT INTO mytable(id,Questions) VALUES (113,'Distal 16p11.2 microdeletion syndrome');
INSERT INTO mytable(id,Questions) VALUES (114,'Drug-induced autoimmune hemolytic anemia');
INSERT INTO mytable(id,Questions) VALUES (115,'Dural sinus malformation');
INSERT INTO mytable(id,Questions) VALUES (116,'Dystonia 9');
INSERT INTO mytable(id,Questions) VALUES (117,'Eales disease');
INSERT INTO mytable(id,Questions) VALUES (118,'Ebola hemorrhagic fever');
INSERT INTO mytable(id,Questions) VALUES (119,'Ectopic aldosterone-producing tumor');
INSERT INTO mytable(id,Questions) VALUES (120,'Enamel hypoplasia, cataracts, and aqueductal stenosis');
INSERT INTO mytable(id,Questions) VALUES (121,'Encephalitis lethargica');
INSERT INTO mytable(id,Questions) VALUES (122,'Encephalopathy, acute, infection-induced (herpes-specific), susceptibility to, 7');
INSERT INTO mytable(id,Questions) VALUES (123,'Enlarged parietal foramina');
INSERT INTO mytable(id,Questions) VALUES (124,'Ependymoma');
INSERT INTO mytable(id,Questions) VALUES (125,'Epilepsy, familial adult myoclonic, 2');
INSERT INTO mytable(id,Questions) VALUES (126,'Epilepsy, familial temporal lobe, 4');
INSERT INTO mytable(id,Questions) VALUES (127,'Episodic ataxia type 1');
INSERT INTO mytable(id,Questions) VALUES (128,'Episodic ataxia type 3');
INSERT INTO mytable(id,Questions) VALUES (129,'Episodic ataxia type 6');
INSERT INTO mytable(id,Questions) VALUES (130,'Episodic ataxia type 7');
INSERT INTO mytable(id,Questions) VALUES (131,'Episodic ataxia with slurred speech');
INSERT INTO mytable(id,Questions) VALUES (132,'Episodic ataxia, type 1');
INSERT INTO mytable(id,Questions) VALUES (133,'Episodic ataxia, type 2');
INSERT INTO mytable(id,Questions) VALUES (134,'Episodic ataxia, type 3');
INSERT INTO mytable(id,Questions) VALUES (135,'Episodic ataxia, type 6');
INSERT INTO mytable(id,Questions) VALUES (136,'Erythrocytosis, familial, 1');
INSERT INTO mytable(id,Questions) VALUES (137,'Erythrocytosis, familial, 2');
INSERT INTO mytable(id,Questions) VALUES (138,'Ethylene glycol poisoning');
INSERT INTO mytable(id,Questions) VALUES (139,'Exercise-induced malignant hyperthermia');
INSERT INTO mytable(id,Questions) VALUES (140,'Familial cerebral cavernous malformation');
INSERT INTO mytable(id,Questions) VALUES (141,'Familial cervical artery dissection');
INSERT INTO mytable(id,Questions) VALUES (142,'Familial cold autoinflammatory syndrome 2');
INSERT INTO mytable(id,Questions) VALUES (143,'Familial cold inflammatory syndrome 1');
INSERT INTO mytable(id,Questions) VALUES (144,'Familial cold urticaria');
INSERT INTO mytable(id,Questions) VALUES (145,'Familial colorectal cancer Type X');
INSERT INTO mytable(id,Questions) VALUES (146,'Familial hyperaldosteronism type I');
INSERT INTO mytable(id,Questions) VALUES (147,'Familial hyperaldosteronism type II');
INSERT INTO mytable(id,Questions) VALUES (148,'Familial hyperaldosteronism type III');
INSERT INTO mytable(id,Questions) VALUES (149,'Familial hypocalciuric hypercalcemia');
INSERT INTO mytable(id,Questions) VALUES (150,'Familial Mediterranean fever, AR');
INSERT INTO mytable(id,Questions) VALUES (151,'Familial or sporadic hemiplegic migraine');
INSERT INTO mytable(id,Questions) VALUES (152,'Familial paroxysmal ataxia');
INSERT INTO mytable(id,Questions) VALUES (153,'Familial thrombocytosis');
INSERT INTO mytable(id,Questions) VALUES (154,'Febrile infection-related epilepsy syndrome');
INSERT INTO mytable(id,Questions) VALUES (155,'Fibromuscular dysplasia, multifocal');
INSERT INTO mytable(id,Questions) VALUES (156,'Functioning gonadotropic adenoma');
INSERT INTO mytable(id,Questions) VALUES (157,'Gaisböck syndrome');
INSERT INTO mytable(id,Questions) VALUES (158,'Gangliocytoma');
INSERT INTO mytable(id,Questions) VALUES (159,'Gaucher disease-ophthalmoplegia-cardiovascular calcification syndrome');
INSERT INTO mytable(id,Questions) VALUES (160,'Genetic steroid-resistant nephrotic syndrome');
INSERT INTO mytable(id,Questions) VALUES (161,'Giant cell arteritis');
INSERT INTO mytable(id,Questions) VALUES (162,'Gitelman syndrome');
INSERT INTO mytable(id,Questions) VALUES (163,'Glioblastoma');
INSERT INTO mytable(id,Questions) VALUES (164,'Glossopharyngeal neuralgia');
INSERT INTO mytable(id,Questions) VALUES (165,'Glut1 deficiency syndrome 2');
INSERT INTO mytable(id,Questions) VALUES (166,'Glutamate monosodium sensitivity');
INSERT INTO mytable(id,Questions) VALUES (167,'Glutaryl-CoA dehydrogenase deficiency');
INSERT INTO mytable(id,Questions) VALUES (168,'Glycogen storage disease due to phosphoglycerate kinase 1 deficiency');
INSERT INTO mytable(id,Questions) VALUES (169,'Granulomatosis with polyangiitis');
INSERT INTO mytable(id,Questions) VALUES (170,'Hajdu-Cheney syndrome');
INSERT INTO mytable(id,Questions) VALUES (171,'Hartnup disease');
INSERT INTO mytable(id,Questions) VALUES (172,'HELLP syndrome');
INSERT INTO mytable(id,Questions) VALUES (173,'Hemangioblastoma');
INSERT INTO mytable(id,Questions) VALUES (174,'Hemifacial atrophy, progressive');
INSERT INTO mytable(id,Questions) VALUES (175,'Hemorrhagic fever-renal syndrome');
INSERT INTO mytable(id,Questions) VALUES (176,'Hereditary hemorrhagic telangiectasia');
INSERT INTO mytable(id,Questions) VALUES (177,'Hereditary pheochromocytoma-paraganglioma');
INSERT INTO mytable(id,Questions) VALUES (178,'Herpes simplex virus encephalitis');
INSERT INTO mytable(id,Questions) VALUES (179,'Hodgkin lymphoma');
INSERT INTO mytable(id,Questions) VALUES (180,'Homocystinuria due to methylene tetrahydrofolate reductase deficiency');
INSERT INTO mytable(id,Questions) VALUES (181,'Hughes-Stovin syndrome');
INSERT INTO mytable(id,Questions) VALUES (182,'Hydroxykynureninuria');
INSERT INTO mytable(id,Questions) VALUES (183,'Hyper-Igd syndrome');
INSERT INTO mytable(id,Questions) VALUES (184,'Hyperammonemia due to N-acetylglutamate synthase deficiency');
INSERT INTO mytable(id,Questions) VALUES (185,'Hyperimmunoglobulinemia D with periodic fever');
INSERT INTO mytable(id,Questions) VALUES (186,'Hypermobile Ehlers-Danlos syndrome');
INSERT INTO mytable(id,Questions) VALUES (187,'Hyperostosis corticalis generalisata');
INSERT INTO mytable(id,Questions) VALUES (188,'Hyperostosis cranialis interna');
INSERT INTO mytable(id,Questions) VALUES (189,'Hyperparathyroidism-jaw tumor syndrome');
INSERT INTO mytable(id,Questions) VALUES (190,'Hyperthermia, cutaneous, with headaches and nausea');
INSERT INTO mytable(id,Questions) VALUES (191,'Hypervalinemia or hyperleucine-isoleucinemia');
INSERT INTO mytable(id,Questions) VALUES (192,'Hypocalciuric hypercalcemia, familial, type III');
INSERT INTO mytable(id,Questions) VALUES (193,'Hypomagnesemia 6, renal');
INSERT INTO mytable(id,Questions) VALUES (194,'Idiopathic intracranial hypertension');
INSERT INTO mytable(id,Questions) VALUES (195,'Idiopathic panuveitis');
INSERT INTO mytable(id,Questions) VALUES (196,'Idiopathic steroid-resistant nephrotic syndrome');
INSERT INTO mytable(id,Questions) VALUES (197,'IgG4-related pachymeningitis');
INSERT INTO mytable(id,Questions) VALUES (198,'Immunodeficiency, developmental delay, and hypohomocysteinemia');
INSERT INTO mytable(id,Questions) VALUES (199,'Immunoglobulin A vasculitis');
INSERT INTO mytable(id,Questions) VALUES (200,'Immunoosseous dysplasia, Schimke type');
INSERT INTO mytable(id,Questions) VALUES (201,'Internal carotid absence');
INSERT INTO mytable(id,Questions) VALUES (202,'Japanese encephalitis');
INSERT INTO mytable(id,Questions) VALUES (203,'Juvenile temporal arteritis');
INSERT INTO mytable(id,Questions) VALUES (204,'Kawasaki disease');
INSERT INTO mytable(id,Questions) VALUES (205,'Kerion celsi');
INSERT INTO mytable(id,Questions) VALUES (206,'L1 syndrome');
INSERT INTO mytable(id,Questions) VALUES (207,'Lafora disease');
INSERT INTO mytable(id,Questions) VALUES (208,'Lassa fever');
INSERT INTO mytable(id,Questions) VALUES (209,'Lead poisoning');
INSERT INTO mytable(id,Questions) VALUES (210,'Legionnaires disease');
INSERT INTO mytable(id,Questions) VALUES (211,'Leptospirosis');
INSERT INTO mytable(id,Questions) VALUES (212,'Leukoencephalopathy with ataxia');
INSERT INTO mytable(id,Questions) VALUES (213,'Lhermitte-Duclos disease');
INSERT INTO mytable(id,Questions) VALUES (214,'Listeriosis');
INSERT INTO mytable(id,Questions) VALUES (215,'Localized scleroderma');
INSERT INTO mytable(id,Questions) VALUES (216,'Loeys-Dietz syndrome 3');
INSERT INTO mytable(id,Questions) VALUES (217,'Lujo hemorrhagic fever');
INSERT INTO mytable(id,Questions) VALUES (218,'Lyme disease');
INSERT INTO mytable(id,Questions) VALUES (219,'Lynch syndrome');
INSERT INTO mytable(id,Questions) VALUES (220,'Maculopapular cutaneous mastocytosis');
INSERT INTO mytable(id,Questions) VALUES (221,'Majeed syndrome');
INSERT INTO mytable(id,Questions) VALUES (222,'Mal de débarquement');
INSERT INTO mytable(id,Questions) VALUES (223,'Malan overgrowth syndrome');
INSERT INTO mytable(id,Questions) VALUES (224,'Malaria');
INSERT INTO mytable(id,Questions) VALUES (225,'Malignant atrophic papulosis');
INSERT INTO mytable(id,Questions) VALUES (226,'Manganese poisoning');
INSERT INTO mytable(id,Questions) VALUES (227,'Marburg hemorrhagic fever');
INSERT INTO mytable(id,Questions) VALUES (228,'Marchiafava-Bignami disease');
INSERT INTO mytable(id,Questions) VALUES (229,'Marsili syndrome');
INSERT INTO mytable(id,Questions) VALUES (230,'Medulloblastoma');
INSERT INTO mytable(id,Questions) VALUES (231,'MELAS');
INSERT INTO mytable(id,Questions) VALUES (232,'Meningioma');
INSERT INTO mytable(id,Questions) VALUES (233,'Meningococcal meningitis');
INSERT INTO mytable(id,Questions) VALUES (234,'Methemoglobinemia due to deficiency of methemoglobin reductase');
INSERT INTO mytable(id,Questions) VALUES (235,'Microcephaly-facial dysmorphism-ocular anomalies-multiple congenital anomalies syndrome');
INSERT INTO mytable(id,Questions) VALUES (236,'Middle ear neuroendocrine tumor');
INSERT INTO mytable(id,Questions) VALUES (237,'Migraine with or without aura, susceptibility to, 1');
INSERT INTO mytable(id,Questions) VALUES (238,'Migraine with or without aura, susceptibility to, 10');
INSERT INTO mytable(id,Questions) VALUES (239,'Migraine with or without aura, susceptibility to, 11');
INSERT INTO mytable(id,Questions) VALUES (240,'Migraine with or without aura, susceptibility to, 12');
INSERT INTO mytable(id,Questions) VALUES (241,'Migraine with or without aura, susceptibility to, 3');
INSERT INTO mytable(id,Questions) VALUES (242,'Migraine with or without aura, susceptibility to, 5');
INSERT INTO mytable(id,Questions) VALUES (243,'Migraine with or without aura, susceptibility to, 6');
INSERT INTO mytable(id,Questions) VALUES (244,'Migraine without aura, susceptibility to, 4');
INSERT INTO mytable(id,Questions) VALUES (245,'Migraine, familial hemiplegic, 1');
INSERT INTO mytable(id,Questions) VALUES (246,'Migraine, familial hemiplegic, 2');
INSERT INTO mytable(id,Questions) VALUES (247,'Migraine, familial hemiplegic, 3');
INSERT INTO mytable(id,Questions) VALUES (248,'Migraine, familial typical, susceptibility to, 2');
INSERT INTO mytable(id,Questions) VALUES (249,'Migraine, with or without aura, susceptibility to, 13');
INSERT INTO mytable(id,Questions) VALUES (250,'Mitochondrial DNA depletion syndrome 12 (cardiomyopathic type)');
INSERT INTO mytable(id,Questions) VALUES (251,'Mitochondrial DNA depletion syndrome 16B (neuroophthalmic type)');
INSERT INTO mytable(id,Questions) VALUES (252,'Mitochondrial DNA depletion syndrome 20 (MNGIE type)');
INSERT INTO mytable(id,Questions) VALUES (253,'Mitochondrial DNA depletion syndrome 7 (hepatocerebral type)');
INSERT INTO mytable(id,Questions) VALUES (254,'Mitochondrial myopathy, encephalopathy, lactic acidosis, and stroke-like episodes');
INSERT INTO mytable(id,Questions) VALUES (255,'Moderate hemophilia A');
INSERT INTO mytable(id,Questions) VALUES (256,'Morgagni-Stewart-Morel syndrome');
INSERT INTO mytable(id,Questions) VALUES (257,'Multiple endocrine neoplasia type 1');
INSERT INTO mytable(id,Questions) VALUES (258,'Multiple endocrine neoplasia type 2');
INSERT INTO mytable(id,Questions) VALUES (259,'Multiple endocrine neoplasia, type IIA');
INSERT INTO mytable(id,Questions) VALUES (260,'Myxopapillary ependymoma');
INSERT INTO mytable(id,Questions) VALUES (261,'Nabais Sa-de vries syndrome, type 2');
INSERT INTO mytable(id,Questions) VALUES (262,'NARP syndrome');
INSERT INTO mytable(id,Questions) VALUES (263,'Neurodegeneration with ataxia and late-onset optic atrophy');
INSERT INTO mytable(id,Questions) VALUES (264,'Neurodevelopmental disorder with hypotonia and dysmorphic facies');
INSERT INTO mytable(id,Questions) VALUES (265,'Neurofibromatosis type 1');
INSERT INTO mytable(id,Questions) VALUES (266,'Neurofibromatosis type 1 due to NF1 mutation or intragenic deletion');
INSERT INTO mytable(id,Questions) VALUES (267,'Neurofibromatosis, type II');
INSERT INTO mytable(id,Questions) VALUES (268,'New-onset refractory status epilepticus');
INSERT INTO mytable(id,Questions) VALUES (269,'Nipah virus disease');
INSERT INTO mytable(id,Questions) VALUES (270,'NMDA receptor encephalitis');
INSERT INTO mytable(id,Questions) VALUES (271,'Nocardiosis');
INSERT INTO mytable(id,Questions) VALUES (272,'Non-functioning paraganglioma');
INSERT INTO mytable(id,Questions) VALUES (273,'Non-functioning pituitary adenoma');
INSERT INTO mytable(id,Questions) VALUES (274,'Non-insulinoma pancreatogenous hypoglycemia syndrome');
INSERT INTO mytable(id,Questions) VALUES (275,'Norrie disease');
INSERT INTO mytable(id,Questions) VALUES (276,'Optic pathway glioma');
INSERT INTO mytable(id,Questions) VALUES (277,'Osteogenesis imperfecta');
INSERT INTO mytable(id,Questions) VALUES (278,'Osteopathia striata with cranial sclerosis');
INSERT INTO mytable(id,Questions) VALUES (279,'Osteopetrosis, autosomal dominant 1');
INSERT INTO mytable(id,Questions) VALUES (280,'Osteosclerosis-developmental delay-craniosynostosis syndrome');
INSERT INTO mytable(id,Questions) VALUES (281,'Paget disease of bone 2, early-onset');
INSERT INTO mytable(id,Questions) VALUES (282,'Panhypophysitis');
INSERT INTO mytable(id,Questions) VALUES (283,'Papillary tumor of the pineal region');
INSERT INTO mytable(id,Questions) VALUES (284,'Papilloma of choroid plexus');
INSERT INTO mytable(id,Questions) VALUES (285,'Paragangliomas 1');
INSERT INTO mytable(id,Questions) VALUES (286,'Paragangliomas 3');
INSERT INTO mytable(id,Questions) VALUES (287,'Paragangliomas 4');
INSERT INTO mytable(id,Questions) VALUES (288,'Parathyroid carcinoma');
INSERT INTO mytable(id,Questions) VALUES (289,'Parietal foramina');
INSERT INTO mytable(id,Questions) VALUES (290,'Parkes Weber syndrome');
INSERT INTO mytable(id,Questions) VALUES (291,'Paroxysmal cold hemoglobinuria');
INSERT INTO mytable(id,Questions) VALUES (292,'Paroxysmal dystonic choreathetosis with episodic ataxia and spasticity');
INSERT INTO mytable(id,Questions) VALUES (293,'Paroxysmal hemicrania');
INSERT INTO mytable(id,Questions) VALUES (294,'Paroxysmal kinesigenic dyskinesia');
INSERT INTO mytable(id,Questions) VALUES (295,'Paroxysmal nocturnal hemoglobinuria');
INSERT INTO mytable(id,Questions) VALUES (296,'Paroxysmal nocturnal hemoglobinuria 2');
INSERT INTO mytable(id,Questions) VALUES (297,'Paroxysmal nonkinesigenic dyskinesia 2');
INSERT INTO mytable(id,Questions) VALUES (298,'Pediatric systemic lupus erythematosus');
INSERT INTO mytable(id,Questions) VALUES (299,'Perineural cyst');
INSERT INTO mytable(id,Questions) VALUES (300,'Periodic fever, familial, autosomal dominant');
INSERT INTO mytable(id,Questions) VALUES (301,'Periodic fever, menstrual cycle-dependent');
INSERT INTO mytable(id,Questions) VALUES (302,'Peripheral primitive neuroectodermal tumor');
INSERT INTO mytable(id,Questions) VALUES (303,'Peroxisome biogenesis disorder 14B');
INSERT INTO mytable(id,Questions) VALUES (304,'PFAPA syndrome');
INSERT INTO mytable(id,Questions) VALUES (305,'PHACE association');
INSERT INTO mytable(id,Questions) VALUES (306,'Phosphoglycerate kinase 1 deficiency');
INSERT INTO mytable(id,Questions) VALUES (307,'Pineoblastoma');
INSERT INTO mytable(id,Questions) VALUES (308,'Pineocytoma');
INSERT INTO mytable(id,Questions) VALUES (309,'Pituicytoma');
INSERT INTO mytable(id,Questions) VALUES (310,'Pituitary apoplexy');
INSERT INTO mytable(id,Questions) VALUES (311,'Pituitary carcinoma');
INSERT INTO mytable(id,Questions) VALUES (312,'Pituitary deficiency due to empty sella turcica syndrome');
INSERT INTO mytable(id,Questions) VALUES (313,'Pituitary deficiency due to Rathke cleft cysts');
INSERT INTO mytable(id,Questions) VALUES (314,'Pituitary dermoid and epidermoid cysts');
INSERT INTO mytable(id,Questions) VALUES (315,'Plague');
INSERT INTO mytable(id,Questions) VALUES (316,'Poliomyelitis');
INSERT INTO mytable(id,Questions) VALUES (317,'Polycythemia vera');
INSERT INTO mytable(id,Questions) VALUES (318,'Pontiac fever');
INSERT INTO mytable(id,Questions) VALUES (319,'Postencephalitic parkinsonism');
INSERT INTO mytable(id,Questions) VALUES (320,'Postorgasmic illness syndrome');
INSERT INTO mytable(id,Questions) VALUES (321,'Preeclampsia');
INSERT INTO mytable(id,Questions) VALUES (322,'Primary angiitis of the central nervous system');
INSERT INTO mytable(id,Questions) VALUES (323,'Primary familial polycythemia');
INSERT INTO mytable(id,Questions) VALUES (324,'Primary hyperaldosteronism-seizures-neurological abnormalities syndrome');
INSERT INTO mytable(id,Questions) VALUES (325,'Primary unilateral adrenal hyperplasia');
INSERT INTO mytable(id,Questions) VALUES (326,'Progressive multifocal leukoencephalopathy');
INSERT INTO mytable(id,Questions) VALUES (327,'Prolactinoma');
INSERT INTO mytable(id,Questions) VALUES (328,'Pulmonary arteriovenous malformation');
INSERT INTO mytable(id,Questions) VALUES (329,'Q fever');
INSERT INTO mytable(id,Questions) VALUES (330,'Rabies');
INSERT INTO mytable(id,Questions) VALUES (331,'Rajab interstitial lung disease with brain calcifications');
INSERT INTO mytable(id,Questions) VALUES (332,'Rat-bite fever');
INSERT INTO mytable(id,Questions) VALUES (333,'Recessive mitochondrial ataxia syndrome');
INSERT INTO mytable(id,Questions) VALUES (334,'Relapsing fever');
INSERT INTO mytable(id,Questions) VALUES (335,'Retinal vasculopathy with cerebral leukoencephalopathy and systemic manifestations');
INSERT INTO mytable(id,Questions) VALUES (336,'Reversible cerebral vasoconstriction syndrome');
INSERT INTO mytable(id,Questions) VALUES (337,'Rhabdoid tumor');
INSERT INTO mytable(id,Questions) VALUES (338,'Rheumatic fever');
INSERT INTO mytable(id,Questions) VALUES (339,'RIDDLE syndrome');
INSERT INTO mytable(id,Questions) VALUES (340,'Rift valley fever');
INSERT INTO mytable(id,Questions) VALUES (341,'Rolandic epilepsy');
INSERT INTO mytable(id,Questions) VALUES (342,'Rosaï-Dorfman disease');
INSERT INTO mytable(id,Questions) VALUES (343,'Sacral defect with anterior meningocele');
INSERT INTO mytable(id,Questions) VALUES (344,'Saethre-Chotzen syndrome');
INSERT INTO mytable(id,Questions) VALUES (345,'Schilder disease');
INSERT INTO mytable(id,Questions) VALUES (346,'Schimke immuno-osseous dysplasia');
INSERT INTO mytable(id,Questions) VALUES (347,'Scleroderma');
INSERT INTO mytable(id,Questions) VALUES (348,'Sclerosteosis 1');
INSERT INTO mytable(id,Questions) VALUES (349,'Scrub typhus');
INSERT INTO mytable(id,Questions) VALUES (350,'Seizures, benign familial infantile, 2');
INSERT INTO mytable(id,Questions) VALUES (351,'Sensory ataxic neuropathy, dysarthria, and ophthalmoparesis');
INSERT INTO mytable(id,Questions) VALUES (352,'Sensory ataxic neuropathy-dysarthria-ophthalmoparesis syndrome');
INSERT INTO mytable(id,Questions) VALUES (353,'Severe acute respiratory syndrome');
INSERT INTO mytable(id,Questions) VALUES (354,'Severe hemophilia A');
INSERT INTO mytable(id,Questions) VALUES (355,'Sheehan syndrome');
INSERT INTO mytable(id,Questions) VALUES (356,'Simple cryoglobulinemia');
INSERT INTO mytable(id,Questions) VALUES (357,'Sneddon syndrome');
INSERT INTO mytable(id,Questions) VALUES (358,'Sneddon syndrome');
INSERT INTO mytable(id,Questions) VALUES (359,'Solar urticaria');
INSERT INTO mytable(id,Questions) VALUES (360,'Somatomammotropinoma');
INSERT INTO mytable(id,Questions) VALUES (361,'Spinocerebellar ataxia 6');
INSERT INTO mytable(id,Questions) VALUES (362,'Spinocerebellar ataxia type 36');
INSERT INTO mytable(id,Questions) VALUES (363,'Splenomegaly, cytopenia, and vision loss');
INSERT INTO mytable(id,Questions) VALUES (364,'Spondyloenchondrodysplasia');
INSERT INTO mytable(id,Questions) VALUES (365,'Sporadic pheochromocytoma/secreting paraganglioma');
INSERT INTO mytable(id,Questions) VALUES (366,'Steroid-responsive encephalopathy associated with autoimmune thyroiditis');
INSERT INTO mytable(id,Questions) VALUES (367,'Stevens-Johnson syndrome/toxic epidermal necrolysis spectrum');
INSERT INTO mytable(id,Questions) VALUES (368,'Stormorken syndrome');
INSERT INTO mytable(id,Questions) VALUES (369,'Striatonigral degeneration, infantile, mitochondrial');
INSERT INTO mytable(id,Questions) VALUES (370,'Subependymoma');
INSERT INTO mytable(id,Questions) VALUES (371,'Sulfide:quinone oxidoreductase deficiency');
INSERT INTO mytable(id,Questions) VALUES (372,'SUNCT syndrome');
INSERT INTO mytable(id,Questions) VALUES (373,'Superficial siderosis');
INSERT INTO mytable(id,Questions) VALUES (374,'Susac syndrome');
INSERT INTO mytable(id,Questions) VALUES (375,'Sydenham chorea');
INSERT INTO mytable(id,Questions) VALUES (376,'Systemic lupus erythematosus 17');
INSERT INTO mytable(id,Questions) VALUES (377,'Systemic mastocytosis with associated hematologic neoplasm');
INSERT INTO mytable(id,Questions) VALUES (378,'Takayasu arteritis');
INSERT INTO mytable(id,Questions) VALUES (379,'Telangiectasia, hereditary hemorrhagic, type 1');
INSERT INTO mytable(id,Questions) VALUES (380,'Telangiectasia, hereditary hemorrhagic, type 2');
INSERT INTO mytable(id,Questions) VALUES (381,'Telangiectasia, hereditary hemorrhagic, type 4');
INSERT INTO mytable(id,Questions) VALUES (382,'TEMPI syndrome');
INSERT INTO mytable(id,Questions) VALUES (383,'Thiamine-responsive megaloblastic anemia syndrome');
INSERT INTO mytable(id,Questions) VALUES (384,'Thrombotic thrombocytopenic purpura');
INSERT INTO mytable(id,Questions) VALUES (385,'Thymic tumor');
INSERT INTO mytable(id,Questions) VALUES (386,'Tick-borne encephalitis');
INSERT INTO mytable(id,Questions) VALUES (387,'Trigeminal neuralgia');
INSERT INTO mytable(id,Questions) VALUES (388,'TSH-secreting pituitary adenoma');
INSERT INTO mytable(id,Questions) VALUES (389,'Tularemia');
INSERT INTO mytable(id,Questions) VALUES (390,'Tumor necrosis factor receptor 1 associated periodic syndrome');
INSERT INTO mytable(id,Questions) VALUES (391,'Tumoral calcinosis, hyperphosphatemic, familial, 3');
INSERT INTO mytable(id,Questions) VALUES (392,'Turcot syndrome with polyposis');
INSERT INTO mytable(id,Questions) VALUES (393,'Typhoid');
INSERT INTO mytable(id,Questions) VALUES (394,'Vascular Ehlers-Danlos syndrome');
INSERT INTO mytable(id,Questions) VALUES (395,'Vasculitis, autoinflammation, immunodeficiency, and hematologic defects syndrome');
INSERT INTO mytable(id,Questions) VALUES (396,'Vasculopathy, retinal, with cerebral leukodystrophy');
INSERT INTO mytable(id,Questions) VALUES (397,'Von Hippel-Lindau disease');
INSERT INTO mytable(id,Questions) VALUES (398,'Waldenström macroglobulinemia');
INSERT INTO mytable(id,Questions) VALUES (399,'Wyburn-Mason syndrome');
INSERT INTO mytable(id,Questions) VALUES (400,'X-linked acrogigantism');
INSERT INTO mytable(id,Questions) VALUES (401,'X-linked adrenoleukodystrophy');
INSERT INTO mytable(id,Questions) VALUES (402,'Yellow fever');
INSERT INTO mytable(id,Questions) VALUES (403,'Zika virus disease');
INSERT INTO mytable(id,Questions) VALUES (404,'Zygomycosis');
